language: node_js
os:
 - windows
 - linux
node_js:
 - '8'
 - '9'
 - '10'
jobs:
  include: 
   - stage: "deploy to github releases"
     os: linux
     node_js: '9'
     deploy:
     provider: releases
     api_key: $GITHUB_OAUTH_TOKEN
     file: lib/app.js
     on:
      tags: true
